# Generated by Django 4.2.1 on 2023-05-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_employer_options'),
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='auth_app.jobseekerprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(related_name='companies', through='job_board.CompanyOwnership', to='auth_app.employerprofile'),
        ),
    ]
