# Generated by Django 4.2.1 on 2023-05-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_company_workers_alter_company_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='workers',
        ),
    ]
