# Generated by Django 4.2.1 on 2023-05-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_jobseekerprofile_company'),
        ('job_board', '0005_alter_vacancy_company_alter_vacancy_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.jobseekerprofile')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_board.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_board.positiontype')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth_app.jobseekerprofile')),
            ],
        ),
    ]
