# Generated by Django 4.2.1 on 2023-05-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0008_rename_vacancyresponses_vacancyresponse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancyresponse',
            old_name='user_profile',
            new_name='user',
        ),
    ]
