# Generated by Django 4.2.1 on 2023-05-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0009_rename_user_profile_vacancyresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
