# Generated by Django 4.2.2 on 2023-06-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0011_vacancy_created_at_vacancy_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at']},
        ),
    ]
