# Generated by Django 4.2.2 on 2023-07-25 05:39

import apps.services.image_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0012_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.services.image_paths.ImagePathsGenerator.get_company_logo),
        ),
    ]
