# Generated by Django 4.2.2 on 2023-08-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_user_bio'),
        ('job_board', '0013_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_board.company')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.employerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='owning_requests',
            field=models.ManyToManyField(related_name='requested_companies', through='job_board.OwningRequest', to='auth_app.employerprofile'),
        ),
    ]
