# Generated by Django 4.2.1 on 2023-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cv'),
        ),
    ]
