# Generated by Django 4.2.1 on 2023-05-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_jobseekerprofile_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={},
        ),
    ]
