# Generated by Django 4.2.1 on 2023-05-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_remove_company_workers'),
        ('auth_app', '0004_alter_employer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='job_board.company'),
            preserve_default=False,
        ),
    ]
