# Generated by Django 4.2.1 on 2023-05-26 06:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0010_vacancy_is_closed_delete_employee'),
        ('auth_app', '0005_jobseekerprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('JOBSEEKER', 'Job seeker'), ('EMPLOYER', 'Owner'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_board.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_board.positiontype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
