# Generated by Django 4.2.1 on 2023-06-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0010_vacancy_is_closed_delete_employee'),
        ('auth_app', '0008_alter_employeeprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job_board.positiontype'),
        ),
    ]
