# Generated by Django 4.2.1 on 2023-06-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_employeeprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='company',
        ),
    ]
