# Generated by Django 4.2.1 on 2023-06-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_remove_jobseekerprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
