# Generated by Django 4.2.2 on 2023-06-27 17:52

import apps.services.image_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_employeeprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.services.image_paths.ImagePathsGenerator.get_avatar_path_user),
        ),
    ]
